blank_issues_enabled: false
contact_links:
    - name: 🤔 Need some help in Integrations
      url: https://razorpay.com/docs/payment-gateway/android-integration/standard/
      about: Looking for help with your app? Please refer to the integration documentation.
